const http = require('node:http');
const crypto = require('node:crypto');

let state = emptyState();
function emptyState(){return {currency:'EUR',minor_units:2,users:[],tokens:[],payments:[],requests:[],splits:[],settlements:[],operators:[],idempotency:[]};}
const now=()=>new Date().toISOString();
const id=(p)=>p+'_'+crypto.randomUUID().replaceAll('-','');
const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj));};
const error=(res,status,code,message=code)=>json(res,status,{error:{code,message}});
function badBody(res){return error(res,400,'malformed_request');}
function parseNumber(x){return typeof x==='number'&&Number.isSafeInteger(x);}
function validAmount(x){return parseNumber(x)&&x>=1&&x<=1e9;}
function clone(x){return JSON.parse(JSON.stringify(x));}
function canonical(x){if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';return JSON.stringify(x);}
function readBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;});req.on('end',()=>{try{resolve(JSON.parse(s||''));}catch(e){reject(e);}});req.on('error',reject);});}
function userByHandle(h){return state.users.find(u=>u.handle===h);}
function userById(i){return state.users.find(u=>u.id===i);}
function receipt(p,viewer){return {...p,settlement_id:p.settlement_id||null};}
function requestOut(r){return {...r};}
function auth(req,res){const h=req.headers.authorization;if(typeof h!=='string'||!h.startsWith('Bearer ')||!h.slice(7)) {error(res,401,'unauthenticated');return null;}const u=state.users.find(x=>x.tokens.includes(h.slice(7)));if(!u)error(res,401,'unauthenticated');return u||null;}
function validFieldTypes(b,allowed){for(const [k,t] of Object.entries(allowed)){if(Object.hasOwn(b,k)&&b[k]!==undefined&&typeof b[k]!==t)return false;}return true;}
function keyInfo(req,res,user,method,path,body){const key=req.headers['idempotency-key'];if(typeof key!=='string'||!key.length){error(res,400,'missing_idempotency_key');return {stop:true};}if(key.length>255)return {stop:true,status:422,code:'validation_failed'};const old=state.idempotency.find(x=>x.user_id===user.id&&x.key===key&&x.method===method&&x.path===path);if(old){if(canonical(old.body)!==canonical(body))return {stop:true,status:409,code:'idempotency_key_reuse'};json(res,200,old.response);return {stop:true};}return {stop:false,key,save:(response)=>state.idempotency.push({user_id:user.id,key,method,path,body:clone(body),response:clone(response)})};}
function amountRule(x){return validAmount(x);}
function payment(from,to,amount,note,visibility,request_id=null,settlement_id=null,created_at=now()){
 from.balance-=amount;to.balance+=amount;
 const p={payment_id:id('p'),from_user_id:from.id,from_handle:from.handle,to_user_id:to.id,to_handle:to.handle,amount,currency:state.currency,note,visibility,request_id,created_at,settlement_id};state.payments.push(p);return p;
}
function page(req,res,who,kind){const q=new URL(req.url,'http://local').searchParams;for(const k of q.keys()){}let limit=50,offset=0;for(const [k,v] of q){if(k==='limit'||k==='offset'){if(!/^\d+$/.test(v))return error(res,422,'validation_failed');const n=Number(v);if(!Number.isSafeInteger(n))return error(res,422,'validation_failed');if(k==='limit')limit=n;else offset=n;}}
 if(limit<1||limit>200||offset<0)return error(res,422,'validation_failed');let rows;
 if(kind==='activity') {rows=state.payments.filter(p=>p.visibility==='public'||p.from_user_id===who.id||p.to_user_id===who.id).sort((a,b)=>b.created_at.localeCompare(a.created_at));}
 else {const dir=q.get('direction'),status=q.get('status');if(dir!==null&&!['incoming','outgoing'].includes(dir))return error(res,422,'validation_failed');if(status!==null&&!['pending','paid','declined','cancelled'].includes(status))return error(res,422,'validation_failed');rows=state.requests.filter(r=>(r.payer_id===who.id||r.requester_id===who.id)&&(!dir||(dir==='incoming'?r.payer_id===who.id:r.requester_id===who.id))&&(!status||r.status===status)).sort((a,b)=>b.created_at.localeCompare(a.created_at));}
 const items=rows.slice(offset,offset+limit);json(res,200,kind==='activity'?{payments:items.map(x=>receipt(x,who)),has_more:offset+limit<rows.length}:{requests:items.map(requestOut),has_more:offset+limit<rows.length});}
function validateFixture(f){if(!f||typeof f!=='object'||Array.isArray(f)||!['EUR','JPY','BHD'].includes(f.currency)||!Number.isInteger(f.minor_units)||!Array.isArray(f.users))return false;const exp={EUR:2,JPY:0,BHD:3};if(f.minor_units!==exp[f.currency])return false;const users=[],ids=new Set(),handles=new Set();for(const x of f.users){if(!x||typeof x!=='object'||typeof x.id!=='string'||!x.id.length||x.id.length>64||typeof x.email!=='string'||typeof x.password!=='string'||typeof x.display_name!=='string'||typeof x.handle!=='string'||!/^[a-z0-9_]{1,20}$/.test(x.handle)||!parseNumber(x.balance)||Math.abs(x.balance)>Number.MAX_SAFE_INTEGER||x.balance<0||ids.has(x.id)||handles.has(x.handle))return false;ids.add(x.id);handles.add(x.handle);const salt=crypto.randomBytes(16).toString('hex'),hash=crypto.scryptSync(x.password,salt,64).toString('hex');users.push({id:x.id,email:x.email,password_hash:hash,password_salt:salt,display_name:x.display_name,handle:x.handle,balance:x.balance,tokens:[]});}
 const byId=i=>users.find(x=>x.id===i);const payments=[];if(f.payments!==undefined&&!Array.isArray(f.payments))return false;for(const p of f.payments||[]){const a=byId(p.from_user_id),b=byId(p.to_user_id);if(!a||!b||!parseNumber(p.amount)||p.amount<0||p.amount>1e9||typeof p.id!=='string'||!p.id.length||p.id.length>64||typeof p.note!=='string'||!['public','private'].includes(p.visibility))return false;payments.push({payment_id:p.id,from_user_id:a.id,from_handle:a.handle,to_user_id:b.id,to_handle:b.handle,amount:p.amount,currency:f.currency,note:p.note,visibility:p.visibility,request_id:null,created_at:typeof p.created_at==='string'?p.created_at:now(),settlement_id:null});}
 if(f.requests!==undefined&&!Array.isArray(f.requests))return false;const requests=[];for(const r of f.requests||[]){const a=byId(r.requester_id),b=byId(r.payer_id);if(!a||!b||!parseNumber(r.amount)||r.amount<0||r.amount>1e9||typeof r.id!=='string'||!r.id.length||r.id.length>64||typeof r.note!=='string'||!['pending','paid','declined','cancelled'].includes(r.status))return false;requests.push({request_id:r.id,requester_id:a.id,requester_handle:a.handle,payer_id:b.id,payer_handle:b.handle,amount:r.amount,currency:f.currency,note:r.note,status:r.status,payment_id:null,created_at:typeof r.created_at==='string'?r.created_at:now()});}
 const operators=Array.isArray(f.settlement_operator_ids)?f.settlement_operator_ids:[];if(operators.some(x=>!byId(x)))return false;
 return {currency:f.currency,minor_units:f.minor_units,users,tokens:[],payments,requests,splits:[],settlements:[],operators,idempotency:[]};}
function importValidate(x){if(!x||x.track!=='pocketful'||x.format_version!==1||!x.state||typeof x.state!=='object'||Array.isArray(x.state))return null;const s=x.state,units={EUR:2,JPY:0,BHD:3};if(units[s.currency]!==s.minor_units)return null;for(const k of ['users','tokens','payments','requests','splits','settlements','operators','idempotency'])if(!Array.isArray(s[k]))return null;try{const z=clone(s),ids=new Set(),handles=new Set();for(const u of z.users){if(!u||typeof u.id!=='string'||!u.id.length||u.id.length>64||typeof u.email!=='string'||typeof u.password_hash!=='string'||typeof u.password_salt!=='string'||typeof u.display_name!=='string'||typeof u.handle!=='string'||!/^[a-z0-9_]{1,20}$/.test(u.handle)||!parseNumber(u.balance)||u.balance<0||!Array.isArray(u.tokens)||u.tokens.some(t=>typeof t!=='string')||ids.has(u.id)||handles.has(u.handle))return null;ids.add(u.id);handles.add(u.handle);}const hasUser=id=>ids.has(id);for(const p of z.payments)if(!p||typeof p.payment_id!=='string'||!p.payment_id.length||p.payment_id.length>64||p.request_id!==null&&(typeof p.request_id!=='string'||!p.request_id.length||p.request_id.length>64)||!hasUser(p.from_user_id)||!hasUser(p.to_user_id)||!parseNumber(p.amount)||p.amount<0||p.amount>1e9||typeof p.note!=='string'||!['public','private'].includes(p.visibility)||typeof p.created_at!=='string')return null;for(const r of z.requests)if(!r||typeof r.request_id!=='string'||!r.request_id.length||r.request_id.length>64||!hasUser(r.requester_id)||!hasUser(r.payer_id)||!parseNumber(r.amount)||r.amount<0||r.amount>1e9||typeof r.note!=='string'||!['pending','paid','declined','cancelled'].includes(r.status)||typeof r.created_at!=='string')return null;if(z.operators.some(id=>!hasUser(id)))return null;for(const k of z.idempotency)if(!k||!hasUser(k.user_id)||typeof k.key!=='string'||!k.key.length||k.key.length>255||typeof k.method!=='string'||typeof k.path!=='string'||!k.body||typeof k.body!=='object'||!k.response||typeof k.response!=='object')return null;return z;}catch{return null;}}
async function handler(req,res){const url=new URL(req.url,'http://local');const path=url.pathname;
 if(req.method==='GET'&&path==='/health')return json(res,200,{status:'ok'});
 if(req.method==='POST'&&path==='/_test/reset'){let b;try{b=await readBody(req);}catch{return badBody(res);}const s=validateFixture(b);if(!s)return error(res,422,'validation_failed');state=s;res.writeHead(204);return res.end();}
 if(req.method==='GET'&&path==='/_test/export')return json(res,200,{track:'pocketful',format_version:1,state:clone(state)});
 if(req.method==='POST'&&path==='/_test/import'){let b;try{b=await readBody(req);}catch{return badBody(res);}const s=importValidate(b);if(!s)return error(res,422,'validation_failed');state=s;res.writeHead(204);return res.end();}
 if(req.method==='POST'&&['/auth/signup','/auth/login'].includes(path)){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);if(!validFieldTypes(b,{email:'string',password:'string',display_name:'string'}))return badBody(res);if(path.endsWith('signup')){if(b.email===undefined||b.password===undefined||b.display_name===undefined)return error(res,422,'validation_failed');if(typeof b.email!=='string'||typeof b.password!=='string'||typeof b.display_name!=='string'||!/^[^@\s]+@[^@\s]+$/.test(b.email)||b.password.length<8)return error(res,422,'validation_failed');if(state.users.some(u=>u.email.toLowerCase()===b.email.toLowerCase()))return error(res,409,'email_taken');const handle=b.email.split('@')[0].toLowerCase().replace(/[^a-z0-9_]/g,'_').slice(0,20);if(userByHandle(handle))return error(res,409,'handle_taken');const salt=crypto.randomBytes(16).toString('hex'),hash=crypto.scryptSync(b.password,salt,64).toString('hex');const u={id:id('u'),email:b.email,password_hash:hash,password_salt:salt,display_name:b.display_name,handle,balance:0,tokens:[]};const token=crypto.randomBytes(32).toString('hex');u.tokens.push(token);state.users.push(u);return json(res,201,{user_id:u.id,display_name:u.display_name,token});}if(b.email===undefined||b.password===undefined)return error(res,422,'validation_failed');const u=state.users.find(x=>x.email.toLowerCase()===String(b.email).toLowerCase());if(!u||!u.password_hash||crypto.scryptSync(String(b.password),u.password_salt,64).toString('hex')!==u.password_hash)return error(res,401,'unauthenticated');const token=crypto.randomBytes(32).toString('hex');u.tokens.push(token);return json(res,200,{user_id:u.id,display_name:u.display_name,token});}
 const user=auth(req,res);if(!user)return;
 if(req.method==='GET'&&path==='/me')return json(res,200,{user_id:user.id,display_name:user.display_name,handle:user.handle,balance:user.balance,currency:state.currency,minor_units:state.minor_units});
 if(req.method==='GET'&&path==='/activity')return page(req,res,user,'activity');if(req.method==='GET'&&path==='/requests')return page(req,res,user,'requests');
 if(req.method==='POST'&&path==='/payments'){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);const k=keyInfo(req,res,user,req.method,path,b);if(k.stop)return k.status?error(res,k.status,k.code):undefined;if(b.to_handle===undefined||b.amount===undefined)return error(res,422,'validation_failed');if(typeof b.to_handle!=='string')return badBody(res);const note=b.note===undefined?'':b.note,vis=b.visibility===undefined?'public':b.visibility;if(!amountRule(b.amount)||typeof note!=='string'||Array.from(note).length>200||!['public','private'].includes(vis))return error(res,422,'validation_failed');const to=userByHandle(b.to_handle);if(!to)return error(res,404,'not_found');if(to.id===user.id)return error(res,422,'self_payment');if(user.balance<b.amount)return error(res,409,'insufficient_funds');if(to.balance+b.amount>Number.MAX_SAFE_INTEGER)return error(res,422,'validation_failed');const p=payment(user,to,b.amount,note,vis);const out={payment_id:p.payment_id,from_user_id:p.from_user_id,from_handle:p.from_handle,to_user_id:p.to_user_id,to_handle:p.to_handle,amount:p.amount,currency:p.currency,note:p.note,visibility:p.visibility,request_id:null,created_at:p.created_at,settlement_id:null};k.save(out);return json(res,201,out);}
 if(req.method==='POST'&&path==='/requests'){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);const k=keyInfo(req,res,user,req.method,path,b);if(k.stop)return k.status?error(res,k.status,k.code):undefined;if(b.payer_handle===undefined||b.amount===undefined)return error(res,422,'validation_failed');if(typeof b.payer_handle!=='string')return badBody(res);const note=b.note===undefined?'':b.note;if(!amountRule(b.amount)||typeof note!=='string'||Array.from(note).length>200)return error(res,422,'validation_failed');const payer=userByHandle(b.payer_handle);if(!payer)return error(res,404,'not_found');if(payer.id===user.id)return error(res,422,'self_request');const r={request_id:id('rq'),requester_id:user.id,requester_handle:user.handle,payer_id:payer.id,payer_handle:payer.handle,amount:b.amount,currency:state.currency,note,status:'pending',payment_id:null,created_at:now()};state.requests.push(r);k.save(r);return json(res,201,r);}
 const match=path.match(/^\/requests\/([^/]+)\/(pay|decline|cancel)$/);if(match){const [,rid,action]=match;let r=state.requests.find(x=>x.request_id===rid);if(!r)return error(res,404,'not_found');if(action==='pay'){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);const k=keyInfo(req,res,user,req.method,path,b);if(k.stop)return k.status?error(res,k.status,k.code):undefined;if(r.payer_id!==user.id)return error(res,403,'forbidden');if(r.status!=='pending')return error(res,409,'request_not_pending');const vis=b.visibility===undefined?'public':b.visibility;if(!['public','private'].includes(vis))return error(res,422,'validation_failed');const from=user,to=userById(r.requester_id);if(from.balance<r.amount)return error(res,409,'insufficient_funds');if(to.balance+r.amount>Number.MAX_SAFE_INTEGER)return error(res,422,'validation_failed');const p=payment(from,to,r.amount,r.note,vis,r.request_id);r.status='paid';r.payment_id=p.payment_id;const out={payment_id:p.payment_id,from_user_id:p.from_user_id,from_handle:p.from_handle,to_user_id:p.to_user_id,to_handle:p.to_handle,amount:p.amount,currency:p.currency,note:p.note,visibility:p.visibility,request_id:p.request_id,created_at:p.created_at,settlement_id:null};k.save(out);return json(res,201,out);}
 if(action==='decline'){if(r.payer_id!==user.id)return error(res,403,'forbidden');if(r.status==='declined')return json(res,200,r);if(r.status!=='pending')return error(res,409,'request_not_pending');r.status='declined';return json(res,200,r);}if(r.requester_id!==user.id)return error(res,403,'forbidden');if(r.status==='cancelled')return json(res,200,r);if(r.status!=='pending')return error(res,409,'request_not_pending');r.status='cancelled';return json(res,200,r);}
 if(req.method==='POST'&&path==='/splits'){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);const k=keyInfo(req,res,user,req.method,path,b);if(k.stop)return k.status?error(res,k.status,k.code):undefined;const hs=b.participant_handles,note=b.note===undefined?'':b.note;if(b.amount===undefined||hs===undefined)return error(res,422,'validation_failed');if(!amountRule(b.amount)||!Array.isArray(hs)||!hs.length||hs.some(x=>typeof x!=='string')||new Set(hs).size!==hs.length||typeof note!=='string'||Array.from(note).length>200)return error(res,422,'validation_failed');const members=hs.map(userByHandle);if(members.some(x=>!x))return error(res,404,'not_found');const count=members.length,base=Math.floor(b.amount/count),extra=b.amount%count;const shares=members.map((u,i)=>({handle:u.handle,amount:base+(i<extra?1:0)}));const created=now(),split_id=id('sp'),requests=[];for(let i=0;i<members.length;i++){const payer=members[i];if(payer.id===user.id)continue;const sh=shares[i];const r={request_id:id('rq'),requester_id:user.id,requester_handle:user.handle,payer_id:payer.id,payer_handle:payer.handle,amount:sh.amount,currency:state.currency,note,status:'pending',payment_id:null,created_at:created};state.requests.push(r);requests.push(r);}const out={split_id,amount:b.amount,currency:state.currency,note,shares,requests,created_at:created};state.splits.push(out);k.save(out);return json(res,201,out);}
 if(req.method==='POST'&&path==='/settlements'){let b;try{b=await readBody(req);}catch{return badBody(res);}if(!b||typeof b!=='object'||Array.isArray(b))return badBody(res);const k=keyInfo(req,res,user,req.method,path,b);if(k.stop)return k.status?error(res,k.status,k.code):undefined;if(!state.operators.includes(user.id))return error(res,403,'forbidden');if(!Array.isArray(b.transfers)||b.transfers.length<1||b.transfers.length>32)return error(res,422,'validation_failed');const transfers=[];for(const t of b.transfers){if(!t||typeof t!=='object'||Array.isArray(t)||typeof t.from_handle!=='string'||typeof t.to_handle!=='string')return error(res,422,'validation_failed');const note=t.note===undefined?'':t.note,vis=t.visibility===undefined?'public':t.visibility;if(!amountRule(t.amount)||typeof note!=='string'||Array.from(note).length>200||!['public','private'].includes(vis))return error(res,422,'validation_failed');const from=userByHandle(t.from_handle),to=userByHandle(t.to_handle);if(!from||!to)return error(res,404,'not_found');if(from.id===to.id)return error(res,422,'self_payment');transfers.push({from,to,amount:t.amount,note,visibility:vis});}const deltas=new Map();for(const t of transfers){deltas.set(t.from.id,(deltas.get(t.from.id)||0)-t.amount);deltas.set(t.to.id,(deltas.get(t.to.id)||0)+t.amount);}if([...deltas].some(([uid,d])=>userById(uid).balance+d<0))return error(res,409,'insufficient_funds');if([...deltas].some(([uid,d])=>userById(uid).balance+d>Number.MAX_SAFE_INTEGER))return error(res,422,'validation_failed');const committed_at=now(),settlement_id=id('st'),payments=transfers.map(t=>({payment_id:id('p'),from_user_id:t.from.id,from_handle:t.from.handle,to_user_id:t.to.id,to_handle:t.to.handle,amount:t.amount,currency:state.currency,note:t.note,visibility:t.visibility,request_id:null,created_at:committed_at,settlement_id}));for(const [uid,d] of deltas)userById(uid).balance+=d;state.payments.push(...payments);const out={settlement_id,committed_at,payments};state.settlements.push(out);k.save(out);return json(res,201,out);}
 return error(res,404,'not_found');
}
const server=http.createServer((req,res)=>{Promise.resolve(handler(req,res)).catch(()=>{if(!res.headersSent)error(res,500,'internal_error');else res.end();});});server.listen(Number(process.env.PORT)||8080,'0.0.0.0');
